name: Carting

on:
  push:
    branches: [ main ]
    paths:
      - 'Carting/**'    
      - /ApiGateway/** 
      - /Shared/**
      - '!.github/workflows/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
env:
    SOLUTION: 'Carting/Carting.sln'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION }}
    - name: Build
      run: dotnet build ${{ env.SOLUTION }} --no-restore
    - name: Test
      run: dotnet test ${{ env.SOLUTION }} --verbosity normal --no-build --logger trx --results-directory "Carting-TestResults.trx"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: Carting-TestResults
        path: Carting-TestResults.trx
      if: ${{ always() }}
