name: Carting

on:
  push:
    branches: [ main ]
    paths:
      - 'Carting/**'    
      - /ApiGateway/** 
      - /Shared/**
      - '!.github/workflows/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test Carting/Carting.sln --verbosity normal --no-build
